apiVersion: apps/v1
kind: Deployment # Deployment object which will create the pods for us. Even restarts if pod stops
metadata:
  name: comments-depl
spec:
  replicas: 1 
  selector: # select the pod we need to deploy based on label in the template
    matchLabels:
      app: comments
  template:
    metadata:
      labels:
        app: comments
    spec:
      containers:
        - name: comments
          image: programmingwithbadri/comments

---
apiVersion: v1
kind: Service
metadata:
  name: comments-srv
spec: # default type: clusterIP
  selector:
    app: comments
  ports:
    - name: comments
      protocol: TCP
      port: 4001 # port number of the current service(cluster IP service).
      targetPort: 4001 # port number of our pod(express server port)