apiVersion: apps/v1
kind: Deployment # Deployment object which will create the pods for us. Even restarts if pod stops
metadata:
  name: event-bus-depl
spec:
  replicas: 1 
  selector: # select the pod we need to deploy based on label in the template
    matchLabels:
      app: event-bus
  template:
    metadata:
      labels:
        app: event-bus
    spec:
      containers:
        - name: event-bus
          image: programmingwithbadri/event-bus

---
apiVersion: v1
kind: Service
metadata:
  name: event-bus-srv
spec: # default type: clusterIP
  selector:
    app: event-bus
  ports:
    - name: event-bus
      protocol: TCP
      port: 4005 # port number of the current service(cluster IP service).
      targetPort: 4005 # port number of our pod(express server port)