apiVersion: apps/v1
kind: Deployment # Deployment object which will create the pods for us. Even restarts if pod stops
metadata:
  name: moderation-depl
spec:
  replicas: 1 
  selector: # select the pod we need to deploy based on label in the template
    matchLabels:
      app: moderation
  template:
    metadata:
      labels:
        app: moderation
    spec:
      containers:
        - name: moderation
          image: programmingwithbadri/moderation

---
apiVersion: v1
kind: Service
metadata:
  name: moderation-srv
spec: # default type: clusterIP
  selector:
    app: moderation
  ports:
    - name: moderation
      protocol: TCP
      port: 4003 # port number of the current service(cluster IP service).
      targetPort: 4003 # port number of our pod(express server port)