apiVersion: apps/v1
kind: Deployment # Deployment object which will create the pods for us. Even restarts if pod stops
metadata:
  name: posts-depl
spec:
  replicas: 1 
  selector: # select the pod we need to deploy based on label in the template
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: programmingwithbadri/posts:0.0.1
