apiVersion: apps/v1
kind: Deployment # Deployment object which will create the pods for us. Even restarts if pod stops
metadata:
  name: posts-depl
spec:
  replicas: 1 
  selector: # select the pod we need to deploy based on label in the template
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: programmingwithbadri/posts
---
apiVersion: v1
kind: Service
metadata:
  name: posts-clusterip-srv # distinguish name between the existing nodeport service
spec: # default type: clusterIP
  selector:
    app: posts
  ports:
    - name: posts
      protocol: TCP
      port: 4000 # port number of the current service(cluster IP service).
      targetPort: 4000 # port number of our pod(express server port)